name: âš¡ Reusable Release

on:
  workflow_call:
    inputs:
      atomi_platform:
        required: true
        type: string
      atomi_service:
        required: true
        type: string

jobs:
  release:
    name: Semantic Release
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-${{ inputs.atomi_platform }}-${{ inputs.atomi_service }}-releaser-nix-store-cache
    steps:
      # Setup
      - uses: AtomiCloud/actions.setup-nix@v2
        with:
          auth-bot-app-id: ${{ vars.AUTH_BOT_APP_ID }}
          auth-bot-secret-key: ${{ secrets.AUTH_BOT_SECRET_KEY }}
      - uses: AtomiCloud/actions.cache-npm@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: nix develop .#releaser -c scripts/ci/release.sh
