name: âš¡ Reusable Test

on:
  workflow_call:
    inputs:
      atomi_platform:
        required: true
        type: string
      atomi_service:
        required: true
        type: string
      test_type:
        required: true
        type: string
        description: 'Test type (unit or int)'
      coverage_target:
        required: true
        type: string
        description: 'Coverage target percentage (e.g. 100)'

jobs:
  test:
    name: Test
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x8-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-${{ inputs.atomi_platform }}-${{ inputs.atomi_service }}-nix-store-cache
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup Nix
      - uses: AtomiCloud/actions.setup-nix@v2

      # Setup Bun cache
      - uses: AtomiCloud/actions.cache-bun@v1

      # Run tests + coverage + threshold
      - name: Run ${{ inputs.test_type }} tests and coverage
        id: run_all
        env:
          TEST_TYPE: ${{ inputs.test_type }}
          COVERAGE_TARGET: ${{ inputs.coverage_target }}
        run: nix develop .#ci -c './scripts/ci/test.sh'
