name: âš¡ Reusable Test

on:
  workflow_call:
    inputs:
      atomi_platform:
        required: true
        type: string
      atomi_service:
        required: true
        type: string
      test_dir:
        required: true
        type: string
        description: 'Test directory (unit or int)'

jobs:
  test:
    name: Test
    runs-on:
      - nscloud-ubuntu-22.04-amd64-4x-with-cache
      - nscloud-cache-size-50gb
      - nscloud-cache-tag-${{ inputs.atomi_platform }}-${{ inputs.atomi_service }}-nix-store-cache
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Setup Nix
      - uses: AtomiCloud/actions.setup-nix@v2

      # Setup Bun cache
      - uses: AtomiCloud/actions.cache-bun@v1

      # Run tests
      - name: Run ${{ inputs.test_dir }} tests
        run: nix develop .#ci -c ./scripts/ci/test-${{ inputs.test_dir }}.sh

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/${{ inputs.test_dir }}/lcov.info
          flags: ${{ inputs.test_dir }}
